Repository Kernel360/KBE5_AntMen_BE, pull requests merged in 2025-07, with the labels that each got.

#165 Feature/#161 matching algorithm
  m-common/src/main/java/com/antmen/antwork/common/service/serviceReservation/MatchingService.java
Labels: Task

#175 매칭 로직 개선: 매니저·수요자 거절 시 즉시 다음 매칭 요청 전송
  m-common/src/main/java/com/antmen/antwork/common/infra/repository/reservation/MatchingRepository.java
  m-common/src/main/java/com/antmen/antwork/common/service/scheduler/MatchingScheduler.java
  m-common/src/main/java/com/antmen/antwork/common/service/serviceReservation/MatchingService.java
Labels: feature

#182 Revert "admin user login block #178"
  LOGGING_SETUP.md
  LOGGING_SYSTEM_NOTION.md
  docker-compose.yml
  env.local.example
  m-admin/src/main/resources/application.yml
  m-admin/src/test/java/com/antmen/antwork/admin/AdminApplicationTests.java
  m-admin/src/test/resources/application-test.yml
  m-admin/src/test/resources/logback-test.xml
  m-common/build.gradle
  m-common/src/main/java/com/antmen/antwork/common/api/controller/AlertController.java
  m-common/src/main/java/com/antmen/antwork/common/api/controller/BoardController.java
  m-common/src/main/java/com/antmen/antwork/common/api/response/alert/AlertEvent.java
  m-common/src/main/java/com/antmen/antwork/common/service/AlertService.java
  m-common/src/main/java/com/antmen/antwork/common/service/serviceAccount/UserService.java
  m-common/src/main/java/com/antmen/antwork/common/service/serviceReservation/MatchingService.java
  m-common/src/main/java/com/antmen/antwork/common/util/WebMvcConfig.java
  m-common/src/main/java/com/antmen/antwork/common/util/log/BusinessLogger.java
  m-common/src/main/java/com/antmen/antwork/common/util/log/LoggingExampleService.java
  m-common/src/main/java/com/antmen/antwork/common/util/log/LoggingInterceptor.java
  m-common/src/main/java/com/antmen/antwork/common/util/log/PerformanceMonitoringAspect.java
  m-common/src/main/resources/application-common-local.yml
  m-common/src/main/resources/application-common-test.yml
  m-common/src/main/resources/application.yml
  m-common/src/main/resources/logback-spring-test.xml
  m-common/src/test/java/com/antmen/antwork/common/CommonApplicationTests.java
  m-common/src/test/resources/application-test.yml
  m-common/src/test/resources/logback-test.xml
  m-customer/src/main/resources/application.yml
  m-customer/src/main/resources/logback-spring.xml
  m-customer/src/test/java/com/antmen/antwork/customer/CustomerApplicationTests.java
  m-customer/src/test/resources/application-test.yml
  m-customer/src/test/resources/logback-test.xml
  m-manager/src/main/resources/application.yml
  m-manager/src/test/java/com/antmen/antwork/manager/ManagerApplicationTests.java
  m-manager/src/test/resources/application-test.yml
  m-manager/src/test/resources/logback-test.xml
  scripts/log-backup-s3.sh
  scripts/run-local-test.sh
  scripts/run-prod.sh
  scripts/setup-logging.sh
Labels: bug, help wanted

#187 Feature/#181 review summary
  m-common/src/main/java/com/antmen/antwork/common/api/response/reservation/MatchingDto.java
  m-common/src/main/java/com/antmen/antwork/common/api/response/reservation/MatchingManagerDetailResponseDto.java
  m-common/src/main/java/com/antmen/antwork/common/api/response/reservation/ReservationDtoConverter.java
  m-common/src/main/java/com/antmen/antwork/common/api/response/reservation/ReviewSummaryResponseDto.java
  m-common/src/main/java/com/antmen/antwork/common/api/response/reservation/UserSummaryDto.java
  m-common/src/main/java/com/antmen/antwork/common/domain/entity/ReviewSummary.java
  m-common/src/main/java/com/antmen/antwork/common/domain/entity/reservation/ReviewAuthorType.java
  m-common/src/main/java/com/antmen/antwork/common/infra/repository/reservation/CalculationRepository.java
  m-common/src/main/java/com/antmen/antwork/common/infra/repository/reservation/ReservationCommentRepository.java
  m-common/src/main/java/com/antmen/antwork/common/infra/repository/reservation/ReviewSummaryRepository.java
  m-common/src/main/java/com/antmen/antwork/common/service/serviceAccount/ManagerService.java
  m-common/src/main/java/com/antmen/antwork/common/service/serviceReservation/ReservationService.java
  m-common/src/main/java/com/antmen/antwork/common/service/serviceReservation/ReviewService.java
  m-common/src/main/java/com/antmen/antwork/common/service/serviceReservation/ReviewSummaryService.java
  m-customer/src/main/java/com/antmen/antwork/customer/controller/CustomerReservationController.java
  m-customer/src/main/java/com/antmen/antwork/customer/controller/CustomerReviewController.java
  m-manager/src/main/java/com/antmen/antwork/manager/controller/ManagerReviewController.java
Labels: feature

#190 Feature/#181 review summary + ssm 적용
  m-customer/src/main/java/com/antmen/antwork/customer/controller/CustomerReviewController.java
Labels: Task

#191 Feature/#166 alert
  m-common/build.gradle
  m-common/src/main/java/com/antmen/antwork/common/api/controller/AlertController.java
  m-common/src/main/java/com/antmen/antwork/common/domain/entity/AlertTrigger.java
  m-common/src/main/java/com/antmen/antwork/common/domain/exception/GlobalExceptionHandler.java
  m-common/src/main/java/com/antmen/antwork/common/service/AlertService.java
  m-common/src/main/java/com/antmen/antwork/common/service/RedisPublisherService.java
  m-common/src/main/java/com/antmen/antwork/common/service/serviceReservation/MatchingService.java
  m-common/src/main/java/com/antmen/antwork/common/service/serviceReservation/PaymentServiceImpl.java
  m-common/src/main/java/com/antmen/antwork/common/service/serviceReservation/ReservationCommentService.java
  m-common/src/main/java/com/antmen/antwork/common/util/AsyncConfig.java
  m-common/src/main/java/com/antmen/antwork/common/util/JwtTokenFilter.java
  m-common/src/main/java/com/antmen/antwork/common/util/RedisConfig.java
  m-common/src/main/resources/application-common-local.yml
  m-common/src/main/resources/application-common-prod.yml
Labels: feature, Task

#200 Feature/#194 관리자 재무관리 기능 구현
  m-admin/src/main/java/com/antmen/antwork/admin/api/AdminCalculationReservationDto.java
  m-admin/src/main/java/com/antmen/antwork/admin/api/AdminCalculationResponseDto.java
  m-admin/src/main/java/com/antmen/antwork/admin/api/AdminMonthCalculationResponseDto.java
  m-admin/src/main/java/com/antmen/antwork/admin/api/AdminSummaryCalculationResponseDto.java
  m-admin/src/main/java/com/antmen/antwork/admin/controller/AdminCaculationController.java
  m-admin/src/main/java/com/antmen/antwork/admin/controller/AdminCalculationController.java
  m-admin/src/main/java/com/antmen/antwork/admin/controller/AdminRefundController.java
  m-admin/src/main/java/com/antmen/antwork/admin/service/AdminCalculationService.java
  m-admin/src/main/java/com/antmen/antwork/admin/service/AdminRefundService.java
  m-admin/src/main/java/com/antmen/antwork/admin/service/AdminSalesStatisticService.java
  m-common/src/main/java/com/antmen/antwork/common/api/response/calculation/CalculationListWithTotalDto.java
  m-common/src/main/java/com/antmen/antwork/common/api/response/calculation/CalculationResponseDto.java
  m-common/src/main/java/com/antmen/antwork/common/infra/repository/reservation/CalculationRepository.java
  m-common/src/main/java/com/antmen/antwork/common/infra/repository/reservation/PaymentRepository.java
  m-manager/src/main/java/com/antmen/antwork/manager/api/ManagerCalculationListWithTotalDto.java
  m-manager/src/main/java/com/antmen/antwork/manager/api/ManagerCalculationResponseDto.java
  m-manager/src/main/java/com/antmen/antwork/manager/controller/ManagerCalculationController.java
  m-manager/src/main/java/com/antmen/antwork/manager/service/ManagerCalculationService.java
Labels: feature

#202 관리자/수요자 옵션 조회 기능 분리 및 URL 구조 정리
  m-admin/src/main/java/com/antmen/antwork/admin/controller/AdminCategoryOptionController.java
  m-admin/src/main/java/com/antmen/antwork/admin/service/AdminCategoryOptionsService.java
  m-common/src/main/java/com/antmen/antwork/common/api/controller/CategoryOptionController.java
  m-common/src/main/java/com/antmen/antwork/common/api/response/reservation/CategoryOptionResponseDto.java
  m-common/src/main/java/com/antmen/antwork/common/domain/entity/reservation/CategoryOption.java
  m-common/src/main/java/com/antmen/antwork/common/service/mapper/reservation/CategoryMapper.java
  m-customer/src/main/java/com/antmen/antwork/customer/api/controller/CustomerCategoryOptionController.java
  m-customer/src/main/java/com/antmen/antwork/customer/service/CustomerCategoryOptionService.java
Labels: Task

#204 Fix: 환불 id 수정, 카테고리 경로 수정
  m-admin/src/main/java/com/antmen/antwork/admin/api/AdminRefundReasonStatisticsDto.java
  m-admin/src/main/java/com/antmen/antwork/admin/api/AdminRefundStatisticsSummaryDto.java
  m-admin/src/main/java/com/antmen/antwork/admin/controller/AdminRefundStatisticsController.java
  m-admin/src/main/java/com/antmen/antwork/admin/service/AdminRefundStatisticsService.java
  m-common/src/main/java/com/antmen/antwork/common/infra/repository/reservation/PaymentRepository.java
  m-common/src/main/java/com/antmen/antwork/common/infra/repository/reservation/RefundRepository.java
  m-customer/src/main/java/com/antmen/antwork/customer/api/controller/CustomerCategoryOptionController.java
  m-customer/src/main/java/com/antmen/antwork/customer/api/request/CustomerRefundRequestDto.java
  m-customer/src/main/java/com/antmen/antwork/customer/service/CustomerRefundService.java
Labels: bug, Task

#225 fix: review null 처리
  m-common/src/main/java/com/antmen/antwork/common/service/serviceReservation/ReservationService.java
Labels: bug
